app_name: cutme
env: prod
log_level: info
base_url: https://cut.me:80

hash_config:
  hash_salt: cutme
  hash_alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  hash_min_length: 7

redis_config:
  host: localhost
  port: 6379
  password:
  redis_hash_key: hash_ids

cassandra_config:
  hosts: ["127.0.0.1"]
  port: 9042
  username: admin
  password: admin
  keyspace: test
  link_table_name: links