app_name: cutme
env: prod
log_level: info
base_url: https://cut.me

hash_config:
  hash_salt: cutme
  hash_alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  hash_min_length: 7

redis_config:
  host: localhost
  port: 6379
  password:
  redis_hash_key: hash_ids